# Generated by Django 4.2.10 on 2024-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.CharField(
                        choices=[(0, "Básico"), (1, "Intermediário"), (2, "Avançado")],
                        default=0,
                        max_length=50,
                    ),
                ),
                ("carga_horaria", models.IntegerField()),
                (
                    "data_do_curso",
                    models.DateField(help_text="Use o formato: YYYY-MM-DD"),
                ),
                ("descricao", models.TextField()),
            ],
            options={
                "verbose_name": "Cadastro de Curso",
                "verbose_name_plural": "Cadastros de Cursos",
                "ordering": ["-data_do_curso", "titulo"],
            },
        ),
    ]
