# Generated by Django 4.2.10 on 2024-02-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="nivel",
            field=models.CharField(
                choices=[
                    ("Iniciante", "Básico"),
                    ("Intermediário", "Intermediário"),
                    ("Avançado", "Avançado"),
                ],
                default=0,
                max_length=50,
            ),
        ),
    ]
