# Generated by Django 4.2.10 on 2024-02-21 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cadastro",
            options={
                "ordering": ["-data"],
                "verbose_name": "Formulário de Cadastro",
                "verbose_name_plural": "Formulários de Cadastros",
            },
        ),
    ]
